my %targets = (
    "Cygwin-aarch64" => {
        inherit_from   => [ "Cygwin-common" ],
        bn_ops         => "SIXTY_FOUR_BIT_LONG",
        asm_arch       => "aarch64",
        perlasm_scheme => "win64",
        shared_argfileflag => "@",
    },
);
