source /etc/makepkg.conf
CARCH=aarch64
CHOST=aarch64-pc-cygwin
PACKAGER='Git for Windows ARM64 Provider <native-provider@example.invalid>'
PKGEXT='.pkg.tar.zst'
COMPRESSZST=(zstd -c -T1 -z -q -)
PKGDEST='/c/ap13-dcb/libxcrypt-successor-packages-01/package-build/packages'
SRCDEST='/c/ap13-dcb/libxcrypt-successor-packages-01/package-build/sources'
SRCPKGDEST='/c/ap13-dcb/libxcrypt-successor-packages-01/package-build/source-packages'
LOGDEST='/c/ap13-dcb/libxcrypt-successor-packages-01/package-build/logs'
BUILDDIR='/c/ap13-dcb/libxcrypt-successor-packages-01/package-build/build'
