#!/bin/bash
# FINAL MinGit-arm64 ASSEMBLY DRIVER  (release.sh:126-181 reproduced against a real installed root)
# Our git package + OUR busybox (1e7a7fd3 handover). Runs where pacman/pactree work (WSL).
# Labelled artefact: MinGit-arm64 (ALL-OURS: every binary/library built with our WoA GCC).
set +e
ML=clangarm64
MK=/mnt/c/Users/CRUTKA~1/AppData/Local/Temp/mkpkg
cache=/mnt/c/Users/CRUTKA~1/AppData/Local/Temp/refpkgs
OURGIT=/mnt/c/Users/crutkasLocal/.copilot/session-state/ea1641ea-57c0-492d-ab94-fcfddedf1091/files/staged-packages/mingw-w64-clang-aarch64-git-2.47.1-1-any.pkg.tar.zst
REPO=/tmp/asm-repo; ROOT=/tmp/asm-root; CONF=/tmp/asm.conf; OVL=/tmp/asm-ovl
PINNED=69b1e704729cf69f0a0c029aa189eb9d38f74fc16ef37823048cb6a98b1523d1
OUT=/mnt/c/Users/crutkasLocal/.copilot/session-state/ea1641ea-57c0-492d-ab94-fcfddedf1091/files/mingit-arm64

echo "############ STEP 0: ensure ephemeral stand-in packages exist (tmp wiped between sessions)"
[ -f /tmp/gcm-pkg/*.pkg.tar.zst ] 2>/dev/null || { tr -d '\r' < "$MK/build-gcm-stub.sh" > /tmp/bgs.sh; bash /tmp/bgs.sh >/dev/null 2>&1; }
ls /tmp/leaves/*.pkg.tar.zst  >/dev/null 2>&1 || { tr -d '\r' < "$MK/build-leaves.sh" > /tmp/bl.sh; bash /tmp/bl.sh >/dev/null 2>&1; }
ls /tmp/bb-pkg/*.pkg.tar.zst  >/dev/null 2>&1 || { tr -d '\r' < "$MK/make-busybox-ours.sh" > /tmp/mbs.sh; bash /tmp/mbs.sh; }
ls /tmp/basestubs/*.pkg.tar.zst >/dev/null 2>&1 || { tr -d '\r' < "$MK/make-base-stubs.sh" > /tmp/mbst.sh; bash /tmp/mbst.sh >/dev/null 2>&1; }

echo "############ STEP 1: assemble sync repo, SWAP OUR REAL GIT for the reference git"
rm -rf "$REPO"; mkdir -p "$REPO"
# reference closure MINUS the reference git package (we ship ours)
for f in "$cache"/*.pkg.tar.zst; do
  bn=$(basename "$f")
  case "$bn" in
    mingw-w64-clang-aarch64-git-2*) echo "  skip reference git: $bn";;
    *) cp "$f" "$REPO"/;;
  esac
done
cp "$OURGIT" "$REPO"/                     # OUR real static git (69b1e704)
cp /tmp/bb-pkg/*.pkg.tar.zst "$REPO"/     # OUR busybox (ash.exe + busybox.exe, 0xAA64, 67665b44)
cp /tmp/gcm-pkg/*.pkg.tar.zst "$REPO"/
cp /tmp/leaves/*.pkg.tar.zst "$REPO"/
cp /tmp/basestubs/*.pkg.tar.zst "$REPO"/
echo "  repo pkgs: $(ls "$REPO"/*.pkg.tar.zst | wc -l)"
echo "  our git in repo: $(ls "$REPO"/mingw-w64-clang-aarch64-git-2* )"
repo-add "$REPO/asm.db.tar.gz" "$REPO"/*.pkg.tar.zst >/tmp/asm-ra.log 2>&1
echo "  repo-add exit=$? added=$(grep -ci 'adding package' /tmp/asm-ra.log)"
printf '[options]\nArchitecture = any\nSigLevel = Never\n\n[asm]\nServer = file://%s\n' "$REPO" > "$CONF"

echo "############ STEP 2: fresh root, install all payloads (-U -dd), populate /clangarm64"
rm -rf "$ROOT"; mkdir -p "$ROOT/var/lib/pacman"
pacman --config "$CONF" --root "$ROOT" --dbpath "$ROOT/var/lib/pacman" -Sy --noconfirm >/tmp/asm-sy.log 2>&1
declare -A seen; instlist=""
for f in "$REPO"/*.pkg.tar.zst; do
  base=$(basename "$f"); pn=$(echo "$base" | sed -E 's/-[0-9].*//')
  if [ -z "${seen[$pn]}" ]; then seen[$pn]=1; instlist="$instlist $f"; fi
done
pacman --config "$CONF" --root "$ROOT" --dbpath "$ROOT/var/lib/pacman" -U --noconfirm -dd $instlist >/tmp/asm-inst.log 2>&1
echo "  install exit=$? ; files under root/$ML: $(find "$ROOT/$ML" -type f 2>/dev/null | wc -l)"
sudo ln -sfn "$ROOT/$ML" /$ML
sudo mkdir -p /var/lib/pacman; sudo rm -rf /var/lib/pacman/local; sudo ln -sfn "$ROOT/var/lib/pacman/local" /var/lib/pacman/local

echo "############ STEP 2a: CONFIRM the installed git.exe is OUR pinned bytes"
GH=$(sha256sum "$ROOT/$ML/bin/git.exe" 2>/dev/null | awk '{print $1}')
echo "  installed git.exe sha256 = $GH"
[ "$GH" = "$PINNED" ] && echo "  PIN OK (matches 69b1e704)" || { echo "  PIN MISMATCH -> ABORT"; exit 4; }
echo "  busybox.exe present: $(ls "$ROOT/$ML/bin/busybox.exe" 2>/dev/null || echo MISSING)"
echo "  ash.exe present:     $(ls "$ROOT/$ML/bin/ash.exe" 2>/dev/null || echo MISSING)"

echo "############ STEP 3b: inject builtins.txt so mfl's builtin trim (mfl:79/341) FIRES"
# UPSTREAM ships share/git/builtins.txt (generated by `make print-builtins` = $(BUILT_INS)).
# Our git package omits it, so the trim silently no-ops and 138 byte-identical builtin
# copies of git.exe survive the libexec->bin fold (the 302 MB bloat). The list was
# generated ON THE ARM64 HOST from our own git.exe (--list-cmds=builtins) in canonical
# git-<name>.exe form (WSL x86-64 cannot execute the ARM64 PE, so it is pre-generated).
mkdir -p "$ROOT/$ML/share/git"
tr -d '\r' < /mnt/c/Users/CRUTKA~1/AppData/Local/Temp/mkpkg/builtins.txt > "$ROOT/$ML/share/git/builtins.txt"
echo "  builtins.txt lines: $(wc -l < "$ROOT/$ML/share/git/builtins.txt") (installed at $ML/share/git/builtins.txt)"
echo "  sample: $(head -3 "$ROOT/$ML/share/git/builtins.txt" | tr '\n' ' ')"

echo "############ STEP 3: rebuild pactree if wiped, set up shims + patched mfl"
if [ ! -x /tmp/pactree ]; then
  cd /tmp; [ -d pacman-contrib ] || git clone --depth 1 https://gitlab.archlinux.org/pacman/pacman-contrib.git >/dev/null 2>&1
  printf '#define PACKAGE_VERSION "1.10.6"\n#define DBPATH "/var/lib/pacman"\n#define CONFFILE "/etc/pacman.conf"\n#define ROOTDIR "/"\n#define GPGDIR "/etc/pacman.d/gnupg"\n#define LOCALEDIR "/usr/share/locale"\n' > /tmp/pt_config.h
  gcc -include /tmp/pt_config.h -o /tmp/pactree pacman-contrib/src/pactree.c -lalpm 2>/dev/null
fi
mkdir -p /tmp/shims
# pacman shim: strip the physical --root prefix from -Ql output so paths anchor at
# /clangarm64/... exactly as release.sh sees them (root == / in a real MSYS install).
# This is what lets the mfl trims (anchored ^/clangarm64/...) actually FIRE.
cat > /tmp/shims/pacman <<SHIM
#!/bin/bash
out=\$(/usr/bin/pacman --config "$CONF" --root "$ROOT" --dbpath "$ROOT/var/lib/pacman" "\$@")
rc=\$?
# normalize any occurrence of the physical root prefix to a bare leading slash
echo "\$out" | sed -e "s#${ROOT}/#/#g" -e "s# ${ROOT#/}/# /#g"
exit \$rc
SHIM
printf '#!/bin/bash\nexec /tmp/pactree --config %s --dbpath %s/var/lib/pacman "$@"\n' "$CONF" "$ROOT" > /tmp/shims/pactree
chmod +x /tmp/shims/*
mkdir -p /tmp/mkpkg; tr -d '\r' < "$MK/mfl-patched.sh" > /tmp/mkpkg/mfl-patched.sh

echo "############ STEP 4: make-file-list WITH_BUSYBOX -> LIST (this is release.sh:94-96 path)"
cd /
LIST="$(PATH=/tmp/shims:$PATH ARCH=aarch64 MINIMAL_GIT_WITH_BUSYBOX=1 \
  bash /tmp/mkpkg/mfl-patched.sh 2>/tmp/asm-mfl.err)"
echo "  make-file-list exit=$? ; LIST lines=$(echo "$LIST" | grep -c .)"
echo "$LIST" | sort > /tmp/asm-list.txt
echo "  --- git.exe / busybox.exe / ash.exe in LIST? ---"
echo "$LIST" | grep -E "/(git|busybox|ash)\.exe$" | sed 's/^/    /'

echo "############ STEP 4a: CONFIRM TRIMS FIRED (absolute-path hazard) - these MUST be ABSENT"
for pat in 'libffi-[0-9]' 'libtasn1-[0-9]' 'p11-kit' 'libpcre2-16' 'libpcre2-32' 'libcurl-4' 'libcrypto-3-arm64' 'libssl-3-arm64' 'libexpat-1'; do
  n=$(echo "$LIST" | grep -cE "$pat")
  echo "    $pat : $n occurrence(s) $( [ "$n" = 0 ] && echo '(absent - trim fired / never pulled)' || echo '<-- PRESENT')"
done

echo "############ STEP 5: overlay assembly (release.sh:126-146) libexec->bin copy"
rm -rf "$OVL"; mkdir -p "$OVL/root"
echo "$LIST" | sort > "$OVL/sorted-all"
PATH=/tmp/shims:$PATH pacman -Ql mingw-w64-clang-aarch64-git | sed 's|^[^ ]* /||' | \
  grep "^$ML/libexec/git-core/.*\.exe$" | sort > "$OVL/sorted-libexec-exes"
echo "  libexec exes from pacman -Ql: $(wc -l < "$OVL/sorted-libexec-exes")"
MOVED=etc/libexec-moved.txt; mkdir -p "$OVL/root/etc"
comm -12 "$OVL/sorted-all" "$OVL/sorted-libexec-exes" > "$OVL/root/$MOVED"
echo "  moved-file entries: $(wc -l < "$OVL/root/$MOVED")"
[ -s "$OVL/root/$MOVED" ] || { echo "  FAIL: no libexec exes in LIST (release.sh:136 die)"; exit 3; }
BIN=$ML/bin; mkdir -p "$OVL/root/$BIN"
(cd / && cp $(cat "$OVL/root/$MOVED") "$OVL/root/$BIN/") && echo "  copied libexec exes into overlay bin/ OK"
sed -e 's|\(.*/\)libexec/git-core\(/.*\)|\1bin\2\n&|' < "$OVL/root/$MOVED" | sort > "$OVL/exclude-list"
LIST2="$(comm -23 "$OVL/sorted-all" "$OVL/exclude-list")"
# Trim pipeline-stubs/ scaffolding: base-stub dep-satisfier packages deposit
# share/pipeline-stubs/*.stub marker files that declare themselves NOT deliverables.
# They exist only so pacman resolves msys2-runtime/openssh/cc-libs/git-extra; the
# marker files must never ship. (Assert the trim fires so it can't silently no-op.)
STUBS_BEFORE=$(echo "$LIST2" | grep -cE "share/pipeline-stubs/")
LIST2="$(echo "$LIST2" | grep -vE "share/pipeline-stubs/")"
STUBS_AFTER=$(echo "$LIST2" | grep -cE "share/pipeline-stubs/")
echo "  pipeline-stubs trim: removed $STUBS_BEFORE marker file(s), $STUBS_AFTER remain"
if [ "$STUBS_AFTER" -ne 0 ]; then echo "  FAIL: pipeline-stubs still present after trim"; exit 10; fi
echo "  LIST after libexec de-dup: $(echo "$LIST2" | grep -c .) lines"
echo "  --- ASSERTION (two-sided): builtin trim fired AND did not over-fire ---"
BINEXE=$(echo "$LIST2" | grep -cE "^$ML/bin/.*\.exe$")
echo "  bin/*.exe in final LIST2: $BINEXE"
if [ "$BINEXE" -gt 40 ]; then
  echo "  FAIL: bin/*.exe count $BINEXE too HIGH -> builtin trim did NOT fire (builtins.txt missing/empty?)"; exit 7
elif [ "$BINEXE" -lt 3 ]; then
  echo "  FAIL: bin/*.exe count $BINEXE too LOW -> trim fired TOO HARD (over-trim; real helpers eaten)"; exit 8
else
  echo "  OK: builtin dashed exes trimmed, real front-ends retained (git.exe dispatches builtins internally)"
fi

echo "############ STEP 6: busybox/ash step (release.sh:160-176)"
case "$LIST2" in *"
$BIN/busybox.exe
"*)
  echo "  LIST contains $BIN/busybox.exe -> entering ash step"
  cp "/$BIN"/busybox.exe "$OVL/root/$BIN"/busybox.exe && echo "  copied busybox.exe into overlay OK"
  # Option-B: real ash.exe applet ships from busybox package; upstream stand-in provides ash.exe.
  if [ -f "/$BIN/ash.exe" ]; then
    cp "/$BIN/ash.exe" "$OVL/root/$BIN"/ash.exe && echo "  copied real ash.exe (Option-B applet) into overlay OK"
  fi
  echo "  (release.sh would ALSO try git-wrapper.exe as ash and probe: ash.exe -c uname == *BusyBox*)"
  rm "$OVL/root/$BIN"/busybox.exe && echo "  removed transient busybox.exe from overlay (per :175)"
  ;;
*) echo "  LIST does NOT contain busybox.exe -> ash step skipped";;
esac

echo "############ STEP 7: build the .zip (host has no 7z; use python zipfile, deflate -9 equiv)"
mkdir -p "$OUT"
TARGET="$OUT/MinGit-2.47.1-arm64.zip"
rm -f "$TARGET"
echo "$LIST2" > /tmp/asm-final-list.txt
python3 - "$TARGET" /tmp/asm-final-list.txt "$OVL/root" "$ML" <<'PY'
import sys, os, zipfile
target, listfile, ovlroot, ml = sys.argv[1:5]
root="/"
added=0; missing=0
with zipfile.ZipFile(target,"w",zipfile.ZIP_DEFLATED,compresslevel=9) as z:
    # 1) files from LIST (installed root)
    for line in open(listfile):
        rel=line.strip()
        if not rel: continue
        src=os.path.join(root, rel)
        if os.path.isfile(src):
            z.write(src, rel); added+=1
        else:
            missing+=1
    # 2) overlay tree (bin/ copies, etc/, license)
    for dp,_,fs in os.walk(ovlroot):
        for fn in fs:
            full=os.path.join(dp,fn); arc=os.path.relpath(full, ovlroot)
            z.write(full, arc); added+=1
print("zip entries added=%d  missing-from-root=%d"%(added,missing))
print("zip bytes=%d"%os.path.getsize(target))
PY
echo "  TARGET=$TARGET"
sha256sum "$TARGET" | tee "$TARGET.sha256"

echo "############ STEP 8: verify the produced artefact"
echo "  --- git.exe inside the zip is our pinned bytes? ---"
python3 - "$TARGET" "$ML" "$PINNED" <<'PY'
import sys,zipfile,hashlib
target,ml,pin=sys.argv[1:4]
z=zipfile.ZipFile(target)
names=z.namelist()
gp=ml+"/bin/git.exe"
if gp in names:
    h=hashlib.sha256(z.read(gp)).hexdigest()
    print("  git.exe in zip:", h, "PIN-OK" if h==pin else "PIN-MISMATCH")
else:
    print("  git.exe NOT in zip at", gp)
print("  total entries:", len(names))
print("  bin/*.exe:", sum(1 for n in names if n.startswith(ml+"/bin/") and n.endswith(".exe")))
print("  ash.exe present:", any(n.endswith(ml+"/bin/ash.exe") or n==ml+"/bin/ash.exe" for n in names))
print("  busybox.exe present (should be ABSENT, removed at :175):", any(n.endswith("/busybox.exe") for n in names))
# busybox pin check: our handover busybox is 67665b44...
bbpin="67665b44db934b574c95a600955482d35f1bb421a9498998df3e5baa96313aa8"
ap=ml+"/bin/ash.exe"
if ap in names:
    ah=hashlib.sha256(z.read(ap)).hexdigest()
    print("  ash.exe (=our busybox):", ah, "BB-PIN-OK" if ah==bbpin else "BB-PIN-MISMATCH")
for pat in ["libffi","libtasn1","p11-kit","libcurl-4","libcrypto-3-arm64","libssl-3-arm64","libexpat-1","libpcre2-8-0"]:
    c=sum(1 for n in names if pat in n)
    print("  %-20s in zip: %d"%(pat,c))
# LOAD-BEARING assertion: the HTTPS clone helpers MUST survive any trim.
required=["git-remote-http","git-remote-https","git-http-fetch","git-http-push"]
missing=[r for r in required if not any(n.endswith("/"+r+".exe") for n in names)]
if missing:
    print("  FAIL: HTTPS clone helper(s) MISSING from zip:", missing); sys.exit(9)
print("  OK: all HTTPS clone helpers present (git-remote-http/https, git-http-fetch/push)")
# non-deliverable scaffolding must not ship
scaffold=[n for n in names if "pipeline-stubs" in n or n.endswith(".stub")]
if scaffold:
    print("  FAIL: non-deliverable scaffolding present in zip:", scaffold); sys.exit(11)
print("  OK: no pipeline-stubs/.stub scaffolding in zip")
PY
echo "############ ASSEMBLY COMPLETE"
