import os, tarfile, io, gzip, hashlib, time, sys, json

# Generic makepkg-compatible package assembler.
# usage: python mkpkg.py <spec.json>
# spec: { pkgname, pkgbase, pkgver, pkgdesc, url, license, depends[], provides[], payload_root, out }
spec = json.load(open(sys.argv[1]))
root = spec["payload_root"]           # dir whose children are clangarm64/...
pkgdir = os.path.dirname(root)
members = []
total = 0
for dp, dn, fn in os.walk(root):
    for f in fn:
        full = os.path.join(dp, f)
        rel = os.path.relpath(full, pkgdir).replace("\\","/")
        with open(full,"rb") as fh: data = fh.read()
        total += len(data)
        members.append((rel, data))
members.sort(key=lambda m: m[0])

builddate = int(time.time())
lines = [
    "# Generated by woa-closure-session makepkg-compatible assembler",
    f"pkgname = {spec['pkgname']}",
    f"pkgbase = {spec['pkgbase']}",
    "xdata = pkgtype=split",
    f"pkgver = {spec['pkgver']}",
    f"pkgdesc = {spec['pkgdesc']}",
    f"url = {spec['url']}",
    f"builddate = {builddate}",
    "packager = WoA native closure session",
    f"size = {total}",
    "arch = any",
    f"license = {spec['license']}",
]
for d in spec.get("depends", []):  lines.append(f"depend = {d}")
for p in spec.get("provides", [spec["pkgname"]]): lines.append(f"provides = {p}")
pkginfo = ("\n".join(lines)+"\n").encode()

mtree_lines = ["#mtree", "/set type=file uid=0 gid=0 mode=644"]
for rel, data in members:
    sha = hashlib.sha256(data).hexdigest(); md5 = hashlib.md5(data).hexdigest()
    mtree_lines.append(f"./{rel} time={builddate}.0 size={len(data)} md5digest={md5} sha256digest={sha}")
mtree_buf = io.BytesIO()
with gzip.GzipFile(fileobj=mtree_buf, mode="wb", mtime=0) as g: g.write(("\n".join(mtree_lines)+"\n").encode())
mtree_gz = mtree_buf.getvalue()
buildinfo = f"format = 2\npkgname = {spec['pkgname']}\npkgver = {spec['pkgver']}\n".encode()

out_tar = spec["out"] + ".tar"
with tarfile.open(out_tar, "w") as tar:
    def add(name, data):
        ti = tarfile.TarInfo(name); ti.size=len(data); ti.mtime=builddate; ti.mode=0o644
        tar.addfile(ti, io.BytesIO(data))
    add(".PKGINFO", pkginfo); add(".BUILDINFO", buildinfo); add(".MTREE", mtree_gz)
    for rel, data in members: add(rel, data)
print("TAR", out_tar, os.path.getsize(out_tar), len(members), "files", total, "installed")
